# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mahasiswa0178.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 865)
        MainWindow.setStyleSheet("background-color:\n"
"qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgb(0, 65, 74))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 771, 801))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageBeranda = QtWidgets.QWidget()
        self.pageBeranda.setObjectName("pageBeranda")
        self.label = QtWidgets.QLabel(self.pageBeranda)
        self.label.setGeometry(QtCore.QRect(50, 10, 671, 81))
        self.label.setStyleSheet("background-color: rgb(0, 65, 75);     /* warna biru */\n"
"color: #2CDE85;                  /* teks putih */\n"
"font-size: 18pt;               /* ukuran font */\n"
"font-weight: bold;            /* teks tebal */\n"
"padding: 220px;                 /* ruang dalam */\n"
"border-radius: 8px;           /* sudut melengkung */\n"
"border-top-color: rgb(170, 255, 255); ")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.pageBeranda)
        self.pushButton.setGeometry(QtCore.QRect(150, 190, 231, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(44, 222, 133);\n"
"border-radius : 8px;\n"
"color: rgb(0, 65, 74);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.pageBeranda)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 190, 231, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(44, 222, 133);\n"
"border-radius : 8px;\n"
"color: rgb(0, 65, 74);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_14 = QtWidgets.QLabel(self.pageBeranda)
        self.label_14.setGeometry(QtCore.QRect(330, 450, 111, 21))
        self.label_14.setStyleSheet("background-color: transparent;\n"
"color : white;")
        self.label_14.setObjectName("label_14")
        self.stackedWidget.addWidget(self.pageBeranda)
        self.pageData = QtWidgets.QWidget()
        self.pageData.setObjectName("pageData")
        self.lineEdit = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit.setGeometry(QtCore.QRect(200, 90, 531, 31))
        self.lineEdit.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(self.pageData)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.pageData)
        self.label_10.setGeometry(QtCore.QRect(20, 340, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.pageData)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 650, 151, 51))
        self.pushButton_5.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_12 = QtWidgets.QLabel(self.pageData)
        self.label_12.setGeometry(QtCore.QRect(440, 850, 291, 31))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.pageData)
        self.label_9.setGeometry(QtCore.QRect(20, 400, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.pageData)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 450, 171, 51))
        self.pushButton_3.setStyleSheet("background-color:  rgb(255, 255, 0);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../xampp/locale/en/LC_MESSAGES/Downloads/pencil-striped-symbol-for-interface-edit-buttons_icon-icons.com_56782.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.pageData)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #2E86C1;     /* warna biru */\n"
"color: white;                  /* teks putih */\n"
"font-size: 15pt;               /* ukuran font */\n"
"font-weight: bold;            /* teks tebal */\n"
"padding: 235px;                 /* ruang dalam */\n"
"border-radius: 8px;           /* sudut melengkung */")
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.pageData)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 650, 201, 51))
        self.pushButton_6.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 210, 531, 31))
        self.lineEdit_4.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.pageData)
        self.label_8.setGeometry(QtCore.QRect(20, 380, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.pageData)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 450, 161, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../xampp/locale/en/LC_MESSAGES/Downloads/emblemunreadable_93487.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLabel(self.pageData)
        self.label_11.setGeometry(QtCore.QRect(420, 650, 291, 31))
        self.label_11.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 130, 531, 31))
        self.lineEdit_2.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.pageData)
        self.pushButton_7.setGeometry(QtCore.QRect(580, 450, 151, 51))
        self.pushButton_7.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../xampp/locale/en/LC_MESSAGES/Downloads/undoarrow_undo_3516.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 170, 531, 31))
        self.lineEdit_3.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 290, 531, 31))
        self.lineEdit_6.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_5 = QtWidgets.QLabel(self.pageData)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.pageData)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 450, 171, 51))
        self.pushButton_8.setStyleSheet("background-color:   rgb(85, 255, 0);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         \n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../xampp/locale/en/LC_MESSAGES/Downloads/add_insert_new_plus_button_icon_142943.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 370, 531, 31))
        self.lineEdit_8.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_4 = QtWidgets.QLabel(self.pageData)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_9.setGeometry(QtCore.QRect(200, 410, 531, 31))
        self.lineEdit_9.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_3 = QtWidgets.QLabel(self.pageData)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.pageData)
        self.tableWidget.setGeometry(QtCore.QRect(20, 510, 711, 131))
        self.tableWidget.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.label_7 = QtWidgets.QLabel(self.pageData)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 250, 531, 31))
        self.lineEdit_5.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.pageData)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 330, 531, 31))
        self.lineEdit_7.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_13 = QtWidgets.QLabel(self.pageData)
        self.label_13.setGeometry(QtCore.QRect(20, 300, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.pushButton_9 = QtWidgets.QPushButton(self.pageData)
        self.pushButton_9.setGeometry(QtCore.QRect(620, 20, 101, 51))
        self.pushButton_9.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.label_6.raise_()
        self.label_10.raise_()
        self.pushButton_5.raise_()
        self.label_12.raise_()
        self.label_9.raise_()
        self.pushButton_3.raise_()
        self.label_2.raise_()
        self.pushButton_6.raise_()
        self.lineEdit_4.raise_()
        self.label_8.raise_()
        self.pushButton_4.raise_()
        self.label_11.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_7.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_6.raise_()
        self.label_5.raise_()
        self.pushButton_8.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.tableWidget.raise_()
        self.label_7.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_7.raise_()
        self.label_13.raise_()
        self.pushButton_9.raise_()
        self.stackedWidget.addWidget(self.pageData)
        self.pageNilai = QtWidgets.QWidget()
        self.pageNilai.setObjectName("pageNilai")
        self.label_41 = QtWidgets.QLabel(self.pageNilai)
        self.label_41.setGeometry(QtCore.QRect(30, 20, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: #2E86C1;     /* warna biru */\n"
"color: white;                  /* teks putih */\n"
"font-size: 15pt;               /* ukuran font */\n"
"font-weight: bold;            /* teks tebal */\n"
"padding: 215px;                 /* ruang dalam */\n"
"border-radius: 8px;           /* sudut melengkung */")
        self.label_41.setObjectName("label_41")
        self.label_27 = QtWidgets.QLabel(self.pageNilai)
        self.label_27.setGeometry(QtCore.QRect(30, 120, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.label_42 = QtWidgets.QLabel(self.pageNilai)
        self.label_42.setGeometry(QtCore.QRect(30, 160, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.pageNilai)
        self.label_43.setGeometry(QtCore.QRect(30, 200, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.pageNilai)
        self.label_44.setGeometry(QtCore.QRect(30, 240, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.pageNilai)
        self.label_45.setGeometry(QtCore.QRect(30, 280, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.pageNilai)
        self.label_46.setGeometry(QtCore.QRect(30, 320, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background: transparent;\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_46.setObjectName("label_46")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.pageNilai)
        self.lineEdit_28.setGeometry(QtCore.QRect(200, 110, 541, 31))
        self.lineEdit_28.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.pageNilai)
        self.lineEdit_29.setGeometry(QtCore.QRect(200, 150, 541, 31))
        self.lineEdit_29.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.pageNilai)
        self.lineEdit_30.setGeometry(QtCore.QRect(200, 190, 541, 31))
        self.lineEdit_30.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.pageNilai)
        self.lineEdit_31.setGeometry(QtCore.QRect(200, 230, 541, 31))
        self.lineEdit_31.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.pageNilai)
        self.lineEdit_32.setGeometry(QtCore.QRect(200, 270, 541, 31))
        self.lineEdit_32.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.pageNilai)
        self.lineEdit_33.setGeometry(QtCore.QRect(200, 310, 541, 31))
        self.lineEdit_33.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.pushButton_03 = QtWidgets.QPushButton(self.pageNilai)
        self.pushButton_03.setGeometry(QtCore.QRect(400, 370, 161, 51))
        self.pushButton_03.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_03.setIcon(icon1)
        self.pushButton_03.setObjectName("pushButton_03")
        self.pushButton_02 = QtWidgets.QPushButton(self.pageNilai)
        self.pushButton_02.setGeometry(QtCore.QRect(210, 370, 171, 51))
        self.pushButton_02.setStyleSheet("background-color:  rgb(255, 255, 0);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_02.setIcon(icon)
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_04 = QtWidgets.QPushButton(self.pageNilai)
        self.pushButton_04.setGeometry(QtCore.QRect(580, 370, 161, 51))
        self.pushButton_04.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_04.setIcon(icon2)
        self.pushButton_04.setObjectName("pushButton_04")
        self.pushButton_05 = QtWidgets.QPushButton(self.pageNilai)
        self.pushButton_05.setGeometry(QtCore.QRect(20, 590, 151, 51))
        self.pushButton_05.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_05.setObjectName("pushButton_05")
        self.pushButton_01 = QtWidgets.QPushButton(self.pageNilai)
        self.pushButton_01.setGeometry(QtCore.QRect(20, 370, 171, 51))
        self.pushButton_01.setStyleSheet("background-color:   rgb(85, 255, 0);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         \n"
"")
        self.pushButton_01.setIcon(icon3)
        self.pushButton_01.setObjectName("pushButton_01")
        self.pushButton_06 = QtWidgets.QPushButton(self.pageNilai)
        self.pushButton_06.setGeometry(QtCore.QRect(200, 590, 201, 51))
        self.pushButton_06.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_06.setObjectName("pushButton_06")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.pageNilai)
        self.tableWidget_4.setGeometry(QtCore.QRect(20, 430, 721, 141))
        self.tableWidget_4.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.pushButton_07 = QtWidgets.QPushButton(self.pageNilai)
        self.pushButton_07.setGeometry(QtCore.QRect(630, 30, 101, 51))
        self.pushButton_07.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black;               \n"
"font-size: 13pt;           \n"
"font-weight: bold;           \n"
"padding: 5px;               \n"
"border-radius: 8px;         ")
        self.pushButton_07.setIcon(icon2)
        self.pushButton_07.setObjectName("pushButton_07")
        self.stackedWidget.addWidget(self.pageNilai)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SELAMAT DATANG"))
        self.pushButton.setText(_translate("MainWindow", " INPUT DATA MAHASISWA"))
        self.pushButton_2.setText(_translate("MainWindow", "INPUT NILAI MAHASISWA"))
        self.label_14.setText(_translate("MainWindow", "©Muhammad Ilmi Nafi"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.label_10.setText(_translate("MainWindow", "MATKUL"))
        self.pushButton_5.setText(_translate("MainWindow", "CLEAR"))
        self.label_9.setText(_translate("MainWindow", "Lokasi Kampus"))
        self.pushButton_3.setText(_translate("MainWindow", "UBAH"))
        self.label_2.setText(_translate("MainWindow", "DATA MAHASISWA"))
        self.pushButton_6.setText(_translate("MainWindow", "LOAD DATA"))
        self.label_8.setText(_translate("MainWindow", "Prodi"))
        self.pushButton_4.setText(_translate("MainWindow", "HAPUS"))
        self.pushButton_7.setText(_translate("MainWindow", "BATAL"))
        self.label_5.setText(_translate("MainWindow", "No.HP"))
        self.pushButton_8.setText(_translate("MainWindow", "TAMBAH"))
        self.label_4.setText(_translate("MainWindow", "Nama Panggilan"))
        self.label_3.setText(_translate("MainWindow", "Nama Lengkap"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama Lengkap"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nama Panggilan"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "No.HP"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "MATKUL"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Prodi"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Lokasi Kampus"))
        self.label_7.setText(_translate("MainWindow", "NPM"))
        self.label_13.setText(_translate("MainWindow", "Kelas"))
        self.pushButton_9.setText(_translate("MainWindow", "KEMBALI"))
        self.label_41.setText(_translate("MainWindow", "INPUT NILAI MAHASISWA"))
        self.label_27.setText(_translate("MainWindow", "ID"))
        self.label_42.setText(_translate("MainWindow", "NPM"))
        self.label_43.setText(_translate("MainWindow", "NILAI HARIAN"))
        self.label_44.setText(_translate("MainWindow", "NILAI TUGAS"))
        self.label_45.setText(_translate("MainWindow", "NILAI UTS"))
        self.label_46.setText(_translate("MainWindow", "NILAI UAS"))
        self.pushButton_03.setText(_translate("MainWindow", "HAPUS"))
        self.pushButton_02.setText(_translate("MainWindow", "UBAH"))
        self.pushButton_04.setText(_translate("MainWindow", "BATAL"))
        self.pushButton_05.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_01.setText(_translate("MainWindow", "TAMBAH"))
        self.pushButton_06.setText(_translate("MainWindow", "LOAD DATA"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NPM"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NILAI HARIAN"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NILAI TUGAS"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NILAI UTS"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "NILAI UAS"))
        self.pushButton_07.setText(_translate("MainWindow", "KEMBALI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
